general {
    lock_cmd = hyprlock
    before_sleep_cmd = hyprlock
}

listener {
    timeout = 90
    on-timeout = brightnessctl set 20%
    on-resume = brightnessctl set 100%
}

listener {
    timeout = 120
    on-timeout = hyprlock
}


